# Generated by Django 5.1.6 on 2025-03-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_tag_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
